FROM node:alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install && apk add --no-cache bash
COPY . .
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
EXPOSE 9000
CMD ["node", "app.js"]
