version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.golang

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app
