# Usa a imagem oficial do MySQL
FROM mysql:latest

# Define variáveis de ambiente para configuração do MySQL
ENV MYSQL_DATABASE=bdfullcycle
ENV MYSQL_USER=mysql
ENV MYSQL_PASSWORD=mysql
ENV MYSQL_ROOT_PASSWORD=root

# Quando o contêiner inicia, ele vai inicializar o banco de dados com estas configurações
EXPOSE 3306
