version: '3'

services:
  db:
    container_name: fullcycle-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dbfullcycle
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password

    ports:
      - "3306:3306"
    networks:
      - networklocal
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    command: /bin/sh -c "chmod +x /wait-for-it.sh && /wait-for-it.sh db:3306 -- node app.js"
    container_name: fullcycle-app
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    networks:
      - networklocal

  nginx:
    container_name: fullcycle-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    networks:
      - networklocal

networks:
  networklocal:
    driver: bridge

volumes:
  mysql_data:

